"""
This is an alternative RL training workflow

This was generated by ChatGPT: "RL LLM Training Workflow"
"""

import torch
import torch.nn as nn
import torch.optim as optim
from transformers import AutoModelForCausalLM, AutoTokenizer
import numpy as np

CACHE_DIR = "/storage/home/hcoda1/6/dfu71/scratch/.cache/huggingface/"
# === Load Pretrained Chatbot Model ===
MODEL_NAME = "microsoft/phi-3.5-mini-instruct"  # Can replace with 'llama2', 'mistral', etc.
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load a pretrained language model for chatbot responses
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, 
                                             cache_dir=CACHE_DIR,
                                             trust_remote_code=True).to(device)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME,
                                          cache_dir = CACHE_DIR,
                                          trust_remote_code=True)

# === Reward Model (Used for Human Feedback) ===
# The reward model predicts a reward score (0-1) for chatbot responses.
# This is a simple neural network applied to the model's hidden states.
class RewardModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(768, 1)  # Linear layer mapping 768-dim hidden state → 1 score
        self.sigmoid = nn.Sigmoid()  # Ensures output is between 0 and 1

    def forward(self, hidden_states):
        # Take the mean of all token embeddings in the sentence, then pass through FC layer
        return self.sigmoid(self.fc(hidden_states.mean(dim=1)))  

reward_model = RewardModel().to(device)  # Move to GPU if available

# === PPO Hyperparameters ===
LEARNING_RATE = 1e-5       # Learning rate for model training
BATCH_SIZE = 4             # How many samples per training step
GAMMA = 0.99               # Discount factor (for advantage computation)
KL_COEFF = 0.1             # Controls how much we penalize divergence from the base model
optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE)  # Optimizer for chatbot

# Simulated dataset with chatbot responses and human-assigned labels
training_data = [
    {"prompt": "Tell me about LangKrash's business model.", "response": "LangKrash connects entrepreneurs using AI matchmaking.", "label": "Good"},
    {"prompt": "What technologies does LangKrash use?", "response": "LangKrash leverages AWS, Docker, and Flask.", "label": "Good"},
    {"prompt": "How does LangKrash's networking system work?", "response": "LangKrash generates random connections.", "label": "Bad"},
]

# === PPO Training Loop ===
for epoch in range(5):  # Train for 5 epochs (iterations over the dataset)
    total_loss = 0  # Track total loss for this epoch

    for data in training_data:
        # Extract prompt, model-generated response, and human feedback label
        prompt, target_response, label = data["prompt"], data["response"], data["label"]
        
        # === Tokenize Input and Target Response ===
        # Convert text into numerical token IDs that the model understands
        input_ids = tokenizer(prompt, return_tensors="pt", truncation=True, padding=True).input_ids.to(device)
        target_ids = tokenizer(target_response, return_tensors="pt", truncation=True, padding=True).input_ids.to(device)
        
        # === Generate a Response from the Chatbot ===
        with torch.no_grad():  # Don't track gradients for inference
            outputs = model.generate(input_ids, max_length=50)  # Generate a response with max length 50
        
        # === Compute Reward using the Reward Model ===
        with torch.no_grad():
            # Extract hidden states from the model (embeddings of the prompt)
            hidden_states = model.transformer(input_ids).last_hidden_state  # Get token embeddings
            reward = reward_model(hidden_states).item()  # Get reward score from reward model
        
        # === Compute PPO Loss ===
        # This consists of policy loss (maximize rewards) + KL regularization (prevent excessive model drift)

        # Get the last token's logits from model output
        logits = model(input_ids).logits[:, -1, :]  # Extract last token prediction
        log_probs = torch.nn.functional.log_softmax(logits, dim=-1)  # Convert logits to log probabilities

        # Extract the log probability of the target token (the correct response token)
        action_log_prob = log_probs.gather(-1, target_ids[:, -1].unsqueeze(-1)).squeeze(-1)

        # Get human-provided reward value (baseline for reward comparison)
        baseline_reward = human_feedback[label]  # Convert label to numerical reward

        # Compute Advantage (How much better the new response is vs. previous response)
        advantage = reward - baseline_reward  

        # Compute PPO policy loss (Maximize reward)
        policy_loss = -advantage * action_log_prob.mean()

        # === KL Divergence Regularization ===
        # This ensures the new model doesn’t deviate too much from the original pretrained LLM.
        with torch.no_grad():
            base_logits = model(input_ids).logits[:, -1, :]  # Get logits from the unmodified pretrained model
            base_log_probs = torch.nn.functional.log_softmax(base_logits, dim=-1)

        kl_div = torch.nn.functional.kl_div(log_probs, base_log_probs, reduction="batchmean")  # Compute KL divergence

        # Final loss function: Policy loss + KL penalty
        loss = policy_loss + KL_COEFF * kl_div

        # === Optimize the Model ===
        optimizer.zero_grad()  # Reset gradients before backpropagation
        loss.backward()  # Compute gradients
        optimizer.step()  # Apply gradient updates to the model parameters

        total_loss += loss.item()  # Track total loss for this epoch

    print(f"Epoch {epoch + 1}, Loss: {total_loss:.4f}")  # Print training progress

print("Training completed!")  # Indicate when training is done

# === Save the Trained Chatbot Model ===
model.save_pretrained("trained_chatbot")  # Save the trained model